version: 0.2

env:
    variables:
        AWS_REGION_NAME: ap-northeast-1
        ECR_REPOSITORY_NAME: sbcntr-backend
        DOCKER_BUILDKIT: "1"
        #SECRET_ARN: XXX CodePipeline で定義
    
phases:
    pre_build:
        commands:
            - AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query 'Account' --output text)
            - aws ecr --region ap-northeast-1 get-login-password | docker login --username AWS --password-stdin https://${AWS_ACCOUNT_ID}.dkr.ecr.ap-northeast-1.amazonaws.com/sbcntr-backend
            - REPOSITORY_URI=${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION_NAME}.amazonaws.com/${ECR_REPOSITORY_NAME}
            # タグ名にGitのコミットハッシュを利用
            - IMAGE_TAG=$(echo ${CODEBUILD_RESOLVED_SOURCE_VERSION} | cut -c 1-7)

    build:
        commands:
            # --build-arg で AWS_ACCOUNT_ID を渡す
            - docker image build --build-arg AWS_ACCOUNT_ID=${AWS_ACCOUNT_ID} -t ${REPOSITORY_URI}:${IMAGE_TAG} .

    post_build:
        commands:
            - docker push ${REPOSITORY_URI}:${IMAGE_TAG}
            - sed -i "s/<AWS_ACCOUNT_ID>/${AWS_ACCOUNT_ID}/g" taskdef.json
            - sed -i "s/<SECRET_ARN>/${SECRET_ARN}/g" taskdef.json
            - printf '{"name":"%s","ImageURI":"%s"}' $ECR_REPOSITORY_NAME $REPOSITORY_URI:$IMAGE_TAG > imageDetail.json

artifacts:
    files:
        - imageDetail.json
      # デプロイステージ用に成果物を追加
        - appspec.yaml
        - taskdef.json
